#!/usr/bin/env node
/**
 * One command to get a working local environment: `npm run setup`.
 *
 * Checks everything that commonly breaks a first run, fixes what it can, and
 * starts the app only once the environment is actually sound. Written in Node
 * rather than PowerShell so it behaves the same on Windows, macOS and the VPS.
 */

import { execSync, spawn, spawnSync } from "node:child_process";
import { existsSync, copyFileSync, readFileSync, writeFileSync } from "node:fs";

const c = {
  cyan: (s) => `\x1b[36m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
};

let healthy = true;
const step = (n) => console.log(c.cyan(`\n== ${n}`));
const good = (m) => console.log(`   ${c.green("OK")}   ${m}`);
const warn = (m) => console.log(`   ${c.yellow("!!")}   ${m}`);
const bad = (m) => {
  console.log(`   ${c.red("XX")}   ${m}`);
  healthy = false;
};

/** Runs a command, returns {ok, out}. Never throws. */
function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, {
    encoding: "utf8",
    shell: process.platform === "win32",
    ...opts,
  });
  return { ok: r.status === 0, out: `${r.stdout ?? ""}${r.stderr ?? ""}` };
}

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---------------------------------------------------------------- Node
step("Node.js");
const major = Number(process.versions.node.split(".")[0]);
if (major < 18) bad(`Node ${process.version} is too old — install Node 20+.`);
else good(`Node ${process.version}`);

// ---------------------------------------------------------------- Config
step("Configuration (.env.local)");
if (!existsSync(".env.local")) {
  warn(".env.local missing — creating it from .env.example");
  copyFileSync(".env.example", ".env.local");
}
const env = readFileSync(".env.local", "utf8");

const value = (key) => {
  const m = env.match(new RegExp(`^${key}=(.*)$`, "m"));
  return m ? m[1].trim() : "";
};

if (!value("ANTHROPIC_API_KEY")) {
  bad(
    "ANTHROPIC_API_KEY is empty.\n" +
      "        Get one at https://console.anthropic.com (add $5 of credit first)\n" +
      "        and paste it into .env.local",
  );
} else {
  good("Anthropic key present");
}

if (!value("ADMIN_SECRET")) warn("ADMIN_SECRET is empty — /admin will reject every login.");
if (value("MOCK_AI") !== "false") {
  warn("MOCK_AI is not 'false' — you'll talk to the scripted stub, not the real agent.");
}

const dbUrl = value("DATABASE_URL");
if (!dbUrl) {
  bad("DATABASE_URL is empty in .env.local");
} else {
  // The Prisma CLI reads `.env` and ignores `.env.local`, so `npx prisma
  // migrate deploy` fails with a confusing "Validation Error ... getConfig"
  // even though the app itself is configured correctly. Mirror just the
  // database URL into `.env` so every Prisma command works — Next.js still
  // prefers `.env.local`, so nothing else changes.
  const mirrored =
    "# Generated by `npm run setup` — the Prisma CLI reads .env, not .env.local.\n" +
    "# Edit DATABASE_URL in .env.local; this file is refreshed automatically.\n" +
    `DATABASE_URL=${dbUrl}\n`;
  const current = existsSync(".env") ? readFileSync(".env", "utf8") : "";
  if (current !== mirrored) writeFileSync(".env", mirrored, "utf8");
  good("DATABASE_URL mirrored to .env for the Prisma CLI");
}

// ---------------------------------------------------------------- Deps
step("Dependencies");
if (!existsSync("node_modules")) {
  warn("node_modules missing — running npm install (takes a minute)");
  run("npm", ["install", "--no-audit", "--no-fund"], { stdio: "inherit" });
}
if (existsSync("node_modules")) good("node_modules present");
else bad("npm install failed");

if (!run("npx", ["prisma", "generate"]).ok) bad("prisma generate failed");
else good("Prisma client generated");

// ---------------------------------------------------------------- Database
step("Database");

/** Only manage the container when DATABASE_URL points at our local one. */
const usesLocalContainer = dbUrl.includes("localhost:5433");

let dbReady = false;
if (!usesLocalContainer) {
  warn("DATABASE_URL points somewhere other than the local container — skipping Docker.");
  dbReady = true;
} else if (!run("docker", ["info"]).ok) {
  warn("Docker is not running — trying to start Docker Desktop");
  if (process.platform === "win32") {
    const dd = "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe";
    if (existsSync(dd)) spawn(dd, { detached: true, stdio: "ignore" }).unref();
  } else if (process.platform === "darwin") {
    run("open", ["-a", "Docker"]);
  }
  for (let i = 0; i < 20; i++) {
    await sleep(5000);
    if (run("docker", ["info"]).ok) break;
  }
  if (!run("docker", ["info"]).ok) {
    bad("Could not start Docker. Open Docker Desktop manually, then run this again.");
  }
}

if (usesLocalContainer && run("docker", ["info"]).ok) {
  good("Docker is running");

  const exists = run("docker", [
    "ps", "-a", "--filter", "name=supportchat-db", "--format", "{{.Names}}",
  ]).out.trim();

  if (!exists) {
    warn("Postgres container missing — creating it on port 5433");
    run("docker", [
      "run", "--name", "supportchat-db",
      "-e", "POSTGRES_PASSWORD=devpass",
      "-e", "POSTGRES_USER=support",
      "-e", "POSTGRES_DB=support",
      "-p", "5433:5432",
      "-d", "postgres:16-alpine",
    ]);
  } else {
    run("docker", ["start", "supportchat-db"]);
  }

  for (let i = 0; i < 15; i++) {
    await sleep(2000);
    if (run("docker", ["exec", "supportchat-db", "pg_isready", "-U", "support"]).ok) {
      dbReady = true;
      break;
    }
  }
  if (dbReady) good("Postgres accepting connections on localhost:5433");
  else bad("Postgres did not come up. Try: docker rm -f supportchat-db, then rerun.");
}

// ---------------------------------------------------------------- Migrations
if (healthy && dbReady) {
  step("Migrations");
  const m = run("npx", ["prisma", "migrate", "deploy"]);
  if (m.ok) good("Schema up to date");
  else bad(`prisma migrate deploy failed:\n${m.out.split("\n").slice(-6).join("\n")}`);
}

// ---------------------------------------------------------------- Port
step("Port 3000");
try {
  if (process.platform === "win32") {
    const pids = execSync(
      'powershell -NoProfile -Command "(Get-NetTCPConnection -LocalPort 3000 -State Listen -ErrorAction SilentlyContinue).OwningProcess"',
      { encoding: "utf8" },
    ).trim();
    if (pids) {
      warn(`Port 3000 in use — stopping process ${pids.split(/\s+/).join(", ")}`);
      for (const pid of new Set(pids.split(/\s+/).filter(Boolean))) {
        run("taskkill", ["/F", "/PID", pid]);
      }
      await sleep(2000);
    }
  } else {
    const pids = run("lsof", ["-ti", ":3000"]).out.trim();
    if (pids) {
      warn("Port 3000 in use — stopping it");
      for (const pid of pids.split("\n").filter(Boolean)) run("kill", ["-9", pid]);
      await sleep(2000);
    }
  }
  good("Port 3000 free");
} catch {
  good("Port 3000 free");
}

// ---------------------------------------------------------------- Start
if (!healthy) {
  console.log(c.red("\nFix the items marked XX above, then run `npm run setup` again.\n"));
  process.exit(1);
}

console.log(c.cyan("\n== Environment is sound. Starting the app...\n"));
console.log("   Customer page : http://localhost:3000");
console.log("   Admin panel   : http://localhost:3000/admin");
console.log("   Talk to it    : node scripts/chat.mjs   (second terminal)");
console.log(c.dim("\n   Ctrl+C to stop.\n"));

spawn("npm", ["run", "dev"], {
  stdio: "inherit",
  shell: process.platform === "win32",
});
